locals {
  # Collect all group names
  all_group_names = distinct(concat(
    [var.groupname],
    keys(var.groups_hierarchy),
    flatten(values(var.groups_hierarchy))
  ))

  # Prepare hosts data once
  all_hosts_data = {
    for h in var.hosts : h.name => merge(
      {
        ansible_host = h.ip
        ansible_user = h.ssh_username
      },
      lookup(var.hosts_vars, h.name, {})
    )
  }

  # Build inventory with null-filtering
  inventory_raw = {
    all = {
      hosts = local.all_hosts_data
      children = {
        for group in local.all_group_names : group => {
          # Use 'null' instead of '{}' to omit empty sections in YAML
          hosts = group == var.groupname ? {
            for h in var.hosts : h.name => {}
          } : null

          children = lookup(var.groups_hierarchy, group, null) != null ? {
            for child in var.groups_hierarchy[group] : child => {}
          } : null
        }
      }
    }
  }

  # Hacks for ansible :
  # remove groups that ended up having neither hosts nor children
  inventory_data = {
    all = {
      hosts = local.inventory_raw.all.hosts
      children = {
        for g_k, g_v in local.inventory_raw.all.children : g_k => {
          for k, v in g_v : k => v if v != null
        } if g_v.hosts != null || g_v.children != null
      }
    }
  }

  # Generate YAML and cleanup
  # Regex to strip quotes from keys while preserving indentation
  # Remove empty braces {} 
  yaml_output = replace(
    replace(
      yamlencode(local.inventory_data),
      "/(?m)^(\\s*)\"([\\w-]+)\":/", # Capture indentation and key name
      "$1$2:"                        # Restore indentation and key without quotes
    ),
    "/: {}/", # Strip empty objects
    ":"
  )


}

resource "local_file" "ansible_hosts_file" {
  filename        = var.inventory_file
  content         = "# File generated by terraform. Do not edit manually\n${local.yaml_output}"
  file_permission = "0644"
}


